[meta]
title = "Flask Transcription Starter"
description = "Get started using Deepgram's Pre-Recorded Transcription with this Flask demo app"
author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
useCase = "STT"
language = "Python"
framework = "Flask"
sdk = "5.3.0"
repository = "https://github.com/deepgram-starters/flask-transcription"

[pre-build]
command = "make init"
message = "Dependencies installed (Python + frontend)"

[build]
command = "make build"
message = "Build completed"

[build.config]
sample = "sample.env"
output = ".env"

[post-build]
message = "Run `make start` to get up and running."
